Port validate_drp algorithms
lsst-dmsst/metric-pipeline-tasks pull request #34
Opened 2020-10-19 20:16 UTC by bechtol

Opening PR to port validate_drp algorithms to new_framework. The comments on the JIRA ticket provide a summary of the functions that need to be ported over.

https://jira.lsstcorp.org/browse/DM-25504

In this initial implementation, I opted to port the functions into three files in the `python/metric_pipeline_utils` folder: `phot_repeat.py` (already existing), `coord_util.py` (new), `tex.py` (new). Below is a summary of where the functions have been moved.

- repeatability (--> `phot_repeat.py`)
  - calcPhotRepeat
  - calcPhotRepeatSample
  - computeWidths
  - getRandomDiffRmsInMmags
  - getRandomDiff
- util
  - averageRaFromCat (--> `coord_util.py`)
  - averageDecFromCat (--> `coord_util.py`)
  - sphDist (--> `coord_util.py`)
  - averageRaDecFromCat (--> `coord_util.py`)
  - medianEllipticity1ResidualsFromCat (--> `tex.py`)
  - medianEllipticity2ResidualsFromCat (--> `tex.py`)
- calcsrd.tex (--> `tex.py`)
  - correlation_function_ellipticity_from_matches
  - select_bin_from_corr
  - correlation_function_ellipticity

In this first commit, I tried to make minimal changes to the validate_drp functions, including doc strings. In a future commit for the PR, it probably makes sense to go through the doc strings at least and clean up references to validate_drp.

2020-10-21 23:18 UTC, SimonKrughoff requested changes
The porting of code looks good, but I think we need tests for all the functions in the utils area.

I'm open for discussion on whether that happens in an independent PR or not.

2020-10-21 23:18 UTC, SimonKrughoff commented on python/metric_pipeline_utils/coord_util.py
> +    dra = ra - ra_mean
I believe the `geom` code in the stack uses the Haversine formula.  It's a little unfortunate that we reimplement it here.  We don't need to change it here, but I'd like an issue in the non-PoC epic to track it.

2020-10-27 22:08 UTC, bechtol commented
I think this is ready for another round of review. I've verified running scons on lsst-devl03.

2020-10-27 23:43 UTC, SimonKrughoff approved these changes
Thanks very much for doing this.  It looks good to me.  We may think about using `setUp` and `tearDown` to reduce some duplication, but that's not important here, and I know the tests I wrote could benefit from that simplification too.

2020-10-28 17:41 UTC, merged